# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('interval', models.IntegerField()),
                ('interval_type', models.CharField(choices=[(b'DAYS', b'Day'), (b'WEEKS', b'Week'), (b'MONTHS', b'Month')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='friends.Friend')),
            ],
        ),
    ]
