# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
