# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20170305_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date',)},
        ),
    ]
